# Configuration for lychee link checker
# See: https://lychee.cli.rs/

cache = true
exclude_all_private = true
exclude_path = ["./node_modules"]
max_cache_age = "10d"
max_redirects = 10
max_retries = 3

exclude = [
    # rate limited / 403 / 503 / whatever
    "https://explorer.celestia-arabica-11.com/",
    "https://arabica.celenium.io/",
    "https://sepolia.arbiscan.io/",
    "https://arbiscan.io/",
    "https://basescan.org/",
    "https://sepolia.basescan.org/",
    "https://etherscan.io/*",
    "https://sepolia.etherscan.io/*",
    "https://holesky.etherscan.io/*",
    "https://scrollscan.com/*",
    "https://celenium.io/",
    "https://mocha.celenium.io",
    "https://mocha-4.celenium.io/",
    "https://celestia-testnet-api.itrocket.net/",
    "https://platform.openai.com/",
    "https://analytics.smartstake.io/",
    # Additional exclusions from failing checks
    "https://x.com/*",
    "https://twitter.com/*",
    "https://explorer.celestia*",
    "mamochain.com",
    "https://polkachu.com/tendermint_snapshots/*",
    "https://polkachu.com/archive_snapshots/*",
    "https://polkachu.com/testnets/*",
    # Social media platforms
    "https://discord.gg/*",
    "https://discord.com/*",
    # Additional exclusions per CI feedback request
    "https://vitepress.dev",
    "https://validao.xyz/*",
    "https://faucet.celestia*",
    "https://dl.acm.org/doi/abs/10.1145/98163.98167",
    # skip any templates used in URLs for `.vitepress/components/*.vue`
    # matches "{.*}" literals in URLs
    '\%7B.*\%7D',
]
