# Configuration for lychee link checker
# See: https://lychee.cli.rs/

cache = true
exclude_all_private = true
exclude_path = ["./node_modules"]
max_cache_age = "10d"
max_redirects = 10
max_retries = 3
# Include local files for checking
include_file = true
# Skip fragments (anchors) as they cause URL encoding issues
exclude_link_local = true

exclude = [
    # rate limited / 403 / 503 / whatever
    "https://explorer.celestia-arabica-11.com/",
    "https://arabica.celenium.io/",
    "https://sepolia.arbiscan.io/",
    "https://arbiscan.io/",
    "https://basescan.org/",
    "https://sepolia.basescan.org/",
    "https://celenium.io/",
    "https://mocha.celenium.io",
    "https://mocha-4.celenium.io/",
    "https://celestia-testnet-api.itrocket.net/",
    "https://platform.openai.com/",
    "https://analytics.smartstake.io/",
    # Social media and communication platforms
    "https://discord.gg/*",
    "https://discord.com/*",
    "https://t.me/*",
    # Additional exclusions from failing checks
    "https://x.com/*",
    "https://twitter.com/*",
    "https://explorer.celestia*",
    "mamochain.com",
    "https://polkachu.com/tendermint_snapshots/*",
    "https://polkachu.com/archive_snapshots/*",
    "https://polkachu.com/testnets/*",
    # GitHub user attachment assets (frequently fail with certificate errors)
    "https://github.com/user-attachments/*",
    "https://github-production-user-asset-*",
    # Common domains that are often blocked or rate-limited
    "https://lumina.rs/*",
    "https://vitalik.eth.limo/*",
    "https://dl.acm.org/*",
    "https://mammoth.celenium.io/*",
    "https://gmamo.vercel.app/*",
    "https://blog.celestia.org/*",
    "https://docs.cosmos.network/*",
    "https://docs.tendermint.com/*",
    "https://docs.arbitrum.io/*",
    "https://www.quicknode.com/*",
    "https://learn.microsoft.com/*",
    "https://docs.celestia.org/*",
    "https://celestiaorg.github.io/*",
    "https://node-rpc-docs.celestia.org/*",
    # Additional frequently failing domains
    "https://celestia.org/*",
    "https://cips.celestia.org/*",
    "https://rollkit.dev/*",
    "https://plausible.celestia.org/*",
    "https://caldera.xyz/*",
    "https://docs.astria.org/*",
    "https://www.mintscan.io/*",
    "https://www.youtube.com/*",
    "https://raas.gelato.network/*",
    "https://conduit.xyz/*",
    "https://docs.dymension.xyz/*",
    "https://platform-docs.succinct.xyz/*",
    "https://etherscan.io/*",
    "https://sepolia.etherscan.io/*",
    "https://geth.ethereum.org/*",
    "https://docs.lightlink.io/*",
    "https://docs.google.com/*",
    "https://jemalloc.net/*",
    "https://stack.optimism.io/*",
    "https://optimism.io/*",
    "https://www.optimism.io/*",
    "https://hackmd.io/*",
    "https://book.getfoundry.sh/*",
    "https://medium.com/*",
    "https://opentelemetry.io/*",
    "https://www.chatbase.co/*",
    "https://pops.one/*",
    # Additional domains that frequently fail
    "https://www.contributor-covenant.org/*",
    "https://forms.gle/*",
    "https://www.rfc-editor.org/*",
    "https://goethereumbook.org/*",
    "https://emsp.gitbook.io/*",
    "https://www.elastic.co/*",
    "https://meetup.com/*",
    "http://meetup.com/*",
    "https://alpha.succinct.xyz/*",
    "https://quicknode.com/*",
    "https://docs.numia.xyz/*",
    "https://www.grove.city/*",
    "https://cosmoslist.co/*",
    "https://figment.io/*",
    "https://multisig.keplr.app/*",
    "https://www.leapwallet.io/*",
    "https://gemwallet.com/*",
    "https://www.keplr.app/*",
    "https://alphab.ai/*",
    "https://explorer.kjnodes.com/*",
    "https://app.leapwallet.io/*",
    "https://wallet.keplr.app/*",
    "https://testnet.keplr.app/*",
    "https://en.wikipedia.org/*",
    # Infrastructure and service providers
    "https://services.kjnodes.com/*",
    "https://itrocket.net/*",
    "https://staking.citizenweb3.com/*",
    "https://snaps.qubelabs.io/*",
    "https://wiki.blackblocks.io/*",
    "https://noders.services/*",
    "https://services.stake-town.com/*",
    "https://services.tienthuattoan.com/*",
    "https://celestia-tools.brightlystake.com/*",
    "https://explorer.chainroot.io/*",
    "https://celestia.valopers.com/*",
    "https://keybase.io/*",
    "https://community.optimism.io/*",
    "https://prometheus.io/*",
    "https://grafana.com/*",
    "https://faucet.celestia/*",
    "https://notes.ethereum.org/*",
    # skip any templates used in URLs for `.vitepress/components/*.vue`
    # matches "{.*}" literals in URLs
    '\%7B.*\%7D',
]