#!/usr/bin/env node

import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = (file) => readFile(new URL(file, root), 'utf8');
const versions = JSON.parse(await read('constants/node_api_versions.json'));
const skill = await read('public/SKILL.md');
const start = '<!-- BEGIN GENERATED NODE API VERSIONS -->';
const end = '<!-- END GENERATED NODE API VERSIONS -->';
assert.equal(skill.split(start).length, 2, 'Expected one skill version block');
assert.equal(skill.split(end).length, 2, 'Expected one skill version block');
assert.ok(skill.indexOf(start) < skill.indexOf(end), 'Invalid skill version markers');

const networks = [['Mainnet Beta', versions.mainnet], ['Mocha', versions.mocha]];
const allVersions = [...networks.map(([, version]) => version), ...versions.historical];
assert.equal(new Set(allVersions).size, allVersions.length, 'Duplicate bundled spec version');
const specs = new Map();
for (const version of allVersions) {
  assert.match(version, /^[\w.-]+$/, 'Invalid bundled spec version');
  const spec = JSON.parse(await read(`public/specs/openrpc-${version}.json`));
  assert.ok(spec.openrpc && Array.isArray(spec.methods) && spec.methods.length,
    `Invalid OpenRPC spec: ${version}`);
  assert.ok(spec.methods.every((method) => typeof method.name === 'string'),
    `Invalid method name in ${version}`);
  specs.set(version, new Set(spec.methods.map((method) => method.name)));
}

// Check the hand-written RPC recommendations without claiming behaviour is validated.
const rpcGuidance = skill.split('## Node RPC method defaults (when direct RPC is requested)')[1]
  ?.split('\n## ')[0].split('\n### ')[0];
assert.ok(rpcGuidance, 'Missing Node RPC guidance');
const methods = [...rpcGuidance.matchAll(/`([a-z]+\.[A-Z]\w+)`/g)].map((match) => match[1]);
assert.ok(methods.length, 'No RPC method recommendations found');
for (const [network, version] of networks) {
  for (const method of methods) {
    assert.ok(specs.get(version).has(method), `${network} ${version} lacks skill method ${method}`);
  }
}

const block = [
  start,
  '<!-- Generated by yarn generate:skill from constants/node_api_versions.json. -->',
  ...networks.map(([network, version]) =>
    `- ${network}: [Node API ${version}](https://docs.celestia.org/build/rpc/node-api/?version=${version}) · [OpenRPC spec](https://docs.celestia.org/specs/openrpc-${version}.json).`),
  end,
].join('\n');
const updated = skill.slice(0, skill.indexOf(start)) + block
  + skill.slice(skill.indexOf(end) + end.length);
if (process.argv.includes('--check')) {
  assert.equal(skill, updated, 'Skill version links are stale. Run yarn generate:skill.');
} else if (skill !== updated) {
  await writeFile(new URL('public/SKILL.md', root), updated);
}
console.log(`Skill version links and ${allVersions.length} bundled specs verified.`);
