const constants = Object.freeze({
  golangNodeCoffee: "1.21.1",
  golangNodeMocha: "1.21.1",
  golangNodeArabica: "1.21.1",
  golangApp: "1.21.1",
  golangCore: "1.21.1",
  golang: "1.21.1",
  arabicaChainId: "arabica-10",
  coffeeChainId: "coffee-0",
  mochaChainId: "mocha-4",
  arabicaRollkitVersion: "v0.10.5",
  mochaRollkitVersion: "v0.10.5",
  coffeeRollkitVersion: "v0.10.5",
  localCelestiaDevnetVersion: "v0.8.2",
  golangBlobstream: "1.20.2",
  orchrelayVersion: "v0.2.0-app-v0.13.2-beta",
  mochaRpcUrl: "https://rpc-mocha.pops.one/",
  mochaRestUrl: "https://api-mocha.pops.one/",
  arabicaRpcUrl: "https://consensus-full.celestia-arabica-10.com/",
  arabicaRestUrl: "https://api.consensus.celestia-arabica-10.com/",
});
export default constants;
