const constants = Object.freeze({
  golangNodeMainnet: "1.21.1",
  golangNodeMocha: "1.21.1",
  golangNodeArabica: "1.21.1",
  golangApp: "1.21.1",
  golangCore: "1.21.1",
  golang: "1.21.1",
  arabicaChainId: "arabica-11",
  mainnetChainId: "celestia",
  mochaChainId: "mocha-4",
  arabicaRollkitVersion: "v0.10.5",
  mochaRollkitVersion: "v0.10.5",
  mainnetRollkitVersion: "v0.10.5",
  localCelestiaDevnetVersion: "v0.8.2",
  golangBlobstream: "1.21.4",
  orchrelayVersion: "v1.0.1",
  mochaRpcUrl: "https://rpc-mocha.pops.one/",
  mochaRestUrl: "https://api-mocha.pops.one/",
  arabicaRpcUrl: "https://consensus-full.celestia-arabica-10.com/",
  arabicaRestUrl: "https://api.consensus.celestia-arabica-10.com/",
  mainnetRpcUrl: "https://rpc.lunaroasis.net/",
  mainnetRestUrl: "https://api.lunaroasis.net/",
});
export default constants;
