name: Build VitePress Site

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn # or pnpm / npm
      - name: Install dependencies
        run: yarn install # or pnpm install / npm ci
      - name: Lint JavaScript/TypeScript
        run: yarn eslint
      - name: Check formatting
        run: yarn prettier --check '**/*.{js,jsx,ts,tsx,md,json,css,scss}'
      - name: Lint Markdown
        run: yarn lint:md
        continue-on-error: true
      - name: Build with VitePress
        run: yarn build # or pnpm build / npm run build 
