name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with Base URL
        run: BASE='/docs-preview/pr-${{ github.event.number }}/' yarn build
        
      - name: Check build output
        run: |
          if [ ! -d ".vitepress/dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi
          echo "Build successful - dist directory contents:"
          ls -la .vitepress/dist

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: .vitepress/dist
          deploy-repository: celestiaorg/docs-preview
          token: ${{ secrets.PREVIEW_DEPLOY }}
          preview-branch: main
          umbrella-dir: .
