name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: BASE_URL='/pr-preview/pr-${{ github.event.number }}/' yarn build
      - name: Add CNAME file
        run: echo docs.celestia.org > ./build/CNAME

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
